include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    unused_local_variable: warning
    invalid_assignment: warning
    invalid_annotation_target: ignore
    missing_return: error
    annotate_overrides: error
    always_specify_types: warning
    dead_code: warning
    todo: info


linter:
  rules:
    prefer_is_not_empty: true
    always_specify_types: true
    avoid_print: true
    prefer_relative_imports: true
    constant_identifier_names: true
    non_constant_identifier_names: true
    avoid_type_to_string: true
    camel_case_types: true
    empty_constructor_bodies: true
    prefer_const_constructors: true
    prefer_single_quotes: true
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_conditional_assignment: true
    cast_nullable_to_non_nullable: true
    always_declare_return_types: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    avoid_void_async: true
    unawaited_futures: true
    await_only_futures: true
    unnecessary_lambdas: true
    unnecessary_await_in_return: true
    prefer_final_fields: true


